force-app/main/default/objects/FeatureSettingsCMT__mdt/FeatureSettingsCMT__mdt.object-meta.xml
<CustomObject>
    <label>FeatureSettingsCMT</label>
    <pluralLabel>FeatureSettingsCMT</pluralLabel>
</CustomObject>

force-app/main/default/objects/FeatureSettingsCMT__mdt/fields/FeatureEnabled__c.field-meta.xml
<CustomField>
    <fullName>FeatureEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FeatureEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordTypeMappingCMT__mdt/RecordTypeMappingCMT__mdt.object-meta.xml
<CustomObject>
    <label>RecordTypeMappingCMT</label>
    <pluralLabel>RecordTypeMappingCMT</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordTypeMappingCMT__mdt/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordTypeMappingCMT__mdt/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordTypeMappingCMT__mdt/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <label>RecordTypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomMetadataService.cls
public with sharing class CustomMetadataService {
    //Return a record that shows whether the RecordTypeMapping feature is enabled
    public FeatureSettingsCMT__mdt getMapperEnablementRecord() {
        FeatureSettingsCMT__mdt enabledRecord = [SELECT Id, FeatureEnabled__c FROM FeatureSettingsCMT__mdt WHERE DeveloperName = 'EnableItPlease' LIMIT 1];
        return enabledRecord;
    }

    //Update the org-level custom setting
    //Returns the original value
    public Boolean updateMapperEnablementRecord(Boolean newValue) {
        Boolean originalValue = getMapperEnablementRecord().FeatureEnabled__c;

        Metadata.DeployContainer container = new Metadata.DeployContainer();
        List<Metadata.Metadata> records = Metadata.Operations.retrieve(Metadata.MetadataType.CustomMetadata, 
                                          new List<String>{'FeatureSettingsCMT.EnableItPlease'});
        if (records.size() > 0) {
            Metadata.CustomMetadata recordToUpdate = (Metadata.CustomMetadata) records.get(0);
            //update the FeatureEnabled__c field
            for (Metadata.CustomMetadataValue fieldAndValue : recordToUpdate.values) {
                if (fieldAndValue.field == 'FeatureEnabled__c') {
                    fieldAndValue.value = newValue;
                }
            }            
            container.addMetadata(recordToUpdate);
            Id asyncResultId = Metadata.Operations.enqueueDeployment(container, null); //could add callback in 2nd param
            System.debug('Updating feature enabled, async id is: ' + asyncResultId);
        }
        return originalValue;        
    }

    //Return a record that shows which record type name to use for the given countryCode
    //and industry values on a new lead.
    public RecordTypeMappingCMT__mdt getRecordTypeMapping(String countryCode, String industry) {
        RecordTypeMappingCMT__mdt mapping = null;

        List<RecordTypeMappingCMT__mdt> mappings =  [SELECT Id, RecordTypeName__c FROM RecordTypeMappingCMT__mdt 
                WHERE CountryCode__c = :countryCode AND Industry__c = :industry];
        if (mappings.size() > 0) {
            mapping = mappings.get(0);
        }
        return mapping;
    }
}