force-app/main/default/objects/RecordTypeMappingCMT__mdt/RecordTypeMappingCMT__mdt.object-meta.xml
<CustomObject>
    <label>RecordTypeMappingCMT</label>
    <pluralLabel>RecordTypeMappingCMT</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordTypeMappingCMT__mdt/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <label>RecordTypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MappingService.cls
public with sharing class MappingService {
    
    CustomMetadataService cmts;

    public MappingService() {
        this.cmts = new CustomMetadataService();
    }

    public String getRecordTypeName(String countryCode, String industry) {
        RecordTypeMappingCMT__mdt mapping = this.cmts.getRecordTypeMapping(countryCode, industry);
        if (mapping != null) {
            return mapping.RecordTypeName__c;
        } else {
            return 'Default Lead';
        }
    }
}